### ISSUE TITLE
Expose cpu.shares specified per container

### ISSUE THREAD

**Issue by brharrington** [intelsdi-x/snap-plugin-collector-docker#25]
In our case there is a max number of shares overall that will be scheduled on a given machine. Shares per container would let us see the requested processing capacity per container and how the actual usage compares to that.

**Comment by marcin-krolik** [comment]
@brharrington would you like to implement it and open PR?

**Comment by brharrington** [comment]
I'll give it a shot when I get some time.

**Comment by marcin-krolik** [comment]
@brharrington cpu.shares added as part of `cgroups_extended` namespace. In next sprint I'm going to refactor the whole plugin and make it more robust and open for future enhancements.
