### ISSUE TITLE
Add Kubernetes labels as tags to docker metrics

### ISSUE THREAD

**Issue by andrzej-k** [intelsdi-x/snap-plugin-collector-docker#43]
It would be good to tag docker metrics collected in Kubernetes environment with Kubernetes labels. Those labels are currently available as a separate metric ```/intel/docker/<docker_id>/spec/labels/<label_key>/value```. This metric shouldn't be removed thou from the list of metrics collected by this plugin.

**Comment by MichalMankowski** [comment]
:+1:
 I want to have possibility to group metrics by pod namespaces or pod/container name. Currently I'm not able to present that on grafana with one query.

**Comment by luizbafilho** [comment]
Those labels give me the possibility to group the metrics like @MichalMankowski asked? If yes, could you show me how?
