### ISSUE TITLE
Only files in /example/tasks should be Task Manifests

### ISSUE THREAD

**Issue by mbbroberg** [intelsdi-x/snap-plugin-collector-docker#54]
There is a lot of non-Task Manifest files in that folder. The folder needs reorganizing to make sense. See [disk](https://github.com/intelsdi-x/snap-plugin-collector-disk/tree/master/examples/tasks) as an example.

**Comment by marcin-krolik** [comment]
@mjbrender Files are organized and there is [README](https://github.com/intelsdi-x/snap-plugin-collector-docker/blob/master/examples/tasks/README.md) as well. These files are dedicated to execute interactive example of `Snap` with docker collector running inside docker. I'm not sure what is your point.

**Comment by mjbrender** [comment]
That's a good point. This file would do better within the /examples folder. Right now it confuses some important language: 

* A *Task Manifest* is a the JSON/YAML file that allows for the creation of a task 
* `.sh` files are not Task Manifest formats 
* `docker-compose.yml` is not a Task Manifest format 

So I guess it only confuses one term :). It's important to make the separate parts of Snap make sense to people and that means a separation between reusable Task Manifests and scripts that help with the scaffolding of testing/demoing Snap.

**Comment by marcin-krolik** [comment]
Got it. I assume it touches all `runnable` examples created so far. As far as I know it would be:
- snap-plugin-collector-disk
- snap-plugin-collector-psutil
- snap-plugin-collector-load
- snap-plugin-collector-meminfo
- snap-plugin-collector-docker
- snap-plugin-publisher-influxdb
