### ISSUE TITLE
Make use of wildcards for metrics

### ISSUE THREAD

**Issue by danielscottt** [intelsdi-x/snap-plugin-collector-docker#8]
Snap's metric types can use `*` for wildcards in a namespace, which allows a one-to-many collection.  

For example, the metric `/intel/linux/docker/<container id>/cpu_stats/cpu_usage/percpu_usage/0` could be represented as`/intel/linux/docker/*/cpu_stats/cpu_usage/percpu_usage/0` which would result in collecting `percpu_usage/0` for all containers on a given host.

**Comment by tiffanyfj** [comment]
Fixed by #9
